apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonete-payment-config
data:
  port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: lanchonete-payment-service
spec:
  selector:
    app: lanchonete-payment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-payment-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lanchonete-payment
  template:
    metadata:
      labels:
        app: lanchonete-payment
    spec:
      containers:
        - name: lanchonete-payment
          image: lanchonete-payment
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: lanchonete-payment-config
                  key: port
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: lanchonete-payment-config
